### ISSUE TITLE
Password encryption key

### ISSUE THREAD

**Issue by danielkucera** [sjanssen15/halotone2mqtt#1]
Hi @sjanssen15 ,

how did you figure out the password encryption method and key?

**Comment by sjanssen15** [comment]
Hi Daniel, I started this project a while ago so I forgot how I got it. But after digiging some more I found out it was your source code I used.

https://github.com/danielkucera/creality-remote-control
This thread: https://www.creationfactory.co/2022/01/rooting-creality-halot-one-resin-3d.html

I'm sorry I didn't credit your work, I will add this to the readme.md if you don't mind?

**Comment by danielkucera** [comment]
Yes, please, thank you :)
